language: python

matrix:
  include:
    - name: "Python 3.8.3"
      python: 3.8.3
      dist: xenial
      before_install:
        - python -m pip install --upgrade pip
      install:
        pip install --user -r req.txt --use-feature=2020-resolver
