language: python

matrix:
  include:
    - name: "Python 3.8"
      python: 3.8
      dist: xenial
      before_install:
        - python -m pip install --upgrade pip
      install:
        pip install kiwisolver
      script: 
        - make test
        - python Windy8Puzzle.py
        
