language: python

jobs:
  include:
    - os: linux
      python: 3.8
      dist: xenial
    - os: windows
      python: 3.8
before_install:
  - python -m pip install --upgrade pip
install:
  pip install kiwisolver
script: 
  - python Windy8Puzzle.py
        
