language: python

matrix:
  include:
    - name: "Python 3.8"
      python: 
        - 3.8
      - os: linux
        arch: amd64
        dist: xenial
      - os: windows
        arch: amd64
      before_install:
        - python -m pip install --upgrade pip
      install:
        pip install kiwisolver
      script: 
        - python Windy8Puzzle.py
        
