language: python

jobs:
  include:
    - os: linux
      python: 3.8
      dist: xenial
before_install:
  - python -m pip install --upgrade pip
install:
  pip install kiwisolver
script: 
  - python Windy8Puzzle.py
  - python test.py
        
